define([], function() {
  return {
    "PropertyPaneDescription": "Description",
    "BasicGroupName": "Group Name",
    "ListNameFieldLabel": "Choose List",
    "ErrorMessage": "List Title field can not be empty",
    "NameDefault": "List",
    "PhoneLabel": "Phone: ",
    "EMailLabel": "E-mail: ",
    "Edit": "Edit",
    "Update": "Update",
    "Create": "Create",
    "NameLabel": "Name: ",
    "PlaceholderName": "Enter contact name",
    "ErrorNameMessage": "Your name must be only 30 symbols",
    "PlaceholderPhone": "Enter phone number 22 222 22 22 or 222 222 222",
    "ErrorPhoneMessage": "Your phone number must be only 12 symbols",
    "PlaceholderEmail": "Enter e-mail address",
    "ImageLabel": "Photo: ",
    "AltImageInfo": "Drop down your photo here",
    "AlertCreateMessage": "Congratulation! Your contact has added",
    "AddNewContact": "Add new contact",
    "PlaceholderSearch": "Search ...",
  }
});